language: python

cache:
  pip: true
  apt: true

sudo: false
dist: trusty


matrix:
  include:
    - env: TEST=standard
      os: linux
      python: '2.7'
    - env: TEST=standard
      os: linux
      python: '3.6'


before_install:
    # Instal miniconda
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - SRC_DIR=$(pwd)


install:
    # Create the python environment ;
    - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION numpy pip;
    - source activate testenv
    # Testing dependencies
    - pip install codecov pytest pytest-cov;
    # Install ephypype
    - cd ${SRC_DIR}
    - pip install -e .


script:
    - if [[ "${TEST}" == "standard" ]]; then
          py.test --cov;
      fi;


notifications:
    email: false


after_success:
    - if [ "${TEST}" == "standard" ]; then
        codecov;
      fi
